### ISSUE TITLE
Is self referencing supported?

### ISSUE THREAD

**Issue by RebeccaStevens** [samthor/esm-resolve#1]
I tried this but it didn't seem to work.

```mjs
import buildResolver from 'esm-resolve';
const r = buildResolver('./subpath/in/my-module');
r('my-module'); // e.g., '../../../index.mjs'
```

**Comment by samthor** [comment]
The issue was I only looked for a peer "package.json" file, not one in parent folders.

I've fixed this and shipped v1.0.7 of this package. Thanks!
