### ISSUE TITLE
Incorrect SPDX identifier for license

### ISSUE THREAD

**Issue by erikreedstrom** [samthor/esm-resolve#2]
The following line for license declaration does not meet SPDX short identifier format for [Apache License 2.0](https://spdx.org/licenses/Apache-2.0.html). This can cause issues with automatic license scanners. 

https://github.com/samthor/esm-resolve/blob/main/package.json#L21

Should be `Apache-2.0`.

**Comment by samthor** [comment]
Out of curiosity, which scanner? deps.dev has no trouble with it.

I'll fix this later when I'm at a computer.
